### ISSUE TITLE
[FEAT] Short Answer Questions

### ISSUE THREAD

**Issue by choco-green** [Preclinify/Tickets#2]
**As a** user, **I want to** be able to answer short answer questions, **so that** I can better prepare for the exam.

Refer to Preclinify/preclinify-dashboard#27

**Comment by rohan-labs** [comment]
{
  "parentQuestion": "Sophie, a 22-year-old woman with a history of asthma, presents to the emergency department with a sudden onset of severe dyspnea, persistent coughing, and audible wheezing. Despite using her salbutamol inhaler multiple times at home, her symptoms have not improved. On examination, her oxygen saturation is 90% on room air, respiratory rate is 26 breaths per minute, heart rate is 110 beats per minute, and the PEFR is 40% of her predicted value. There is no evidence of cyanosis or altered mental status, but she appears distressed and is unable to complete sentences in one breath. A chest X-ray indicates hyperinflated lung fields with no signs of pneumothorax or infection.",
  "subQuestions": [
    {
      "question": "Considering her presentation and the initial assessment, what is the most appropriate next step in management?",
      "idealAnswer": "Administer high-flow oxygen to maintain SpO2 between 94-98% and provide high-dose inhaled SABA like salbutamol via a nebulizer. This approach aims to quickly improve oxygenation and bronchodilation."
    },
    {
      "question": "If her condition does not improve significantly with initial treatments, what additional therapy should be considered?",
      "idealAnswer": "Add Ipratropium bromide as a nebulized treatment combined with systemic corticosteroids, specifically Prednisolone 40-50 mg orally daily for at least five days or until clinical recovery is observed."
    },
    {
      "question": "Based on the severity of her asthma exacerbation, what criteria should be met before considering her for discharge?",
      "idealAnswer": "Stability on discharge medication for at least 12-24 hours, confirmed proper inhaler technique, and PEFR greater than 75% of her best or predicted value, ensuring she can manage her asthma effectively outside the hospital."
    }
  ]
}

**Comment by choco-green** [comment]
Update: All sub questions should be shown at once for each parent question, there will be 1 submit button to submit all answers at once. Each sub question should be marked seperately.
