### ISSUE TITLE
[BUG] Invalid password in sign up handled wrongly

### ISSUE THREAD

**Issue by choco-green** [Preclinify/Tickets#24]
## Describe the bug
When signing up, a length of at least 6 is required from the user, however the route pushes to login even if this isn't achieved. Further, the toast indicates that it is both a successful operation and an unsuccessful operation

**Comment by highjeans** [comment]
I just tested this by using another email of mine with a password with 3 characters, and 1. the route doesn't push to login and 2. the toast only shows the unsuccessful operation.

**Comment by highjeans** [comment]
@Joecey For me to do this ticket, I would need to change a function in the `AuthenticationForm` component, which @choco-green is going to make changes to at some point. Should I wait for him to make those changes or should I go ahead and finish this ticket?

**Comment by Joecey** [comment]
Better to consult @choco-green but I think you can go ahead and finish the ticket. No active branch from his end ATM so fire away 👌

**Comment by highjeans** [comment]
Closes #64
