### ISSUE TITLE
[FEAT] Viewing the percentage of students selecting each option within a multiple choice question

### ISSUE THREAD

**Issue by rahulsagu** [Preclinify/Tickets#30]
*As a user*, I would like to view the percentage of students who selected each option (A-E) within an MCQ, so this will help us when classifying the difficulty of questions and this will allow the user to see what proportion of students answered what option. The percentages of students submitting each option should appear at the side of each option once the user has submitted an answer for a question in endless mode, as they are reviewing if they correctly or incorrectly answer the question. In exam mode, these percentages should be viewable after all questions have been attempted, where the student is able to review each of the questions.

**Comment by Joecey** [comment]
Loop with with #29
