### ISSUE TITLE
[FEAT] Reference ranges 

### ISSUE THREAD

**Issue by rahulsagu** [Preclinify/Tickets#33]
**As a** user, I want to view reference ranges for the various common laboratory investigations so that I can easily interpret data presented within MCQs and SAQs as I answer them. They should be available in both Exam mode and Endless mode. This can appear as a pop-up upon clicking an icon at the side of the page to allow the user to view them and scroll down to view the appropriate reference ranges. 

Note - the reference ranges can be found within the "Questions" folder within the Preclinify shared Google Drive. They have been organised according to the types of investigations. :)

**Comment by Joecey** [comment]
Do these change at all depending on question type?

**Comment by rahulsagu** [comment]
Hey I'm sorry I didn't get back to you for a while - this does not change with the question type!!

**Comment by Joecey** [comment]
This needs to be added to both endless and exam modes

**Comment by Joecey** [comment]
Whoever does this, it would be good if you're able to make this into a component so then we can implement it in endless now. Then, we can add it to exam mode once complete
