### ISSUE TITLE
[FEAT] Landing page for closed beta launch

### ISSUE THREAD

**Issue by rohan-labs** [Preclinify/Tickets#40]
## User Story

**As a** user,  **I want to navigate between SAQ, MCQ and OSCE bot pages on the website from the landing page**. This is to replace the current dashboard page that reads "This is the dashboard Page"

## Additional context
As discussed this can be simply designed links which navigate through each aspect of the website. No worries about pretty UI for now.

**Comment by Joecey** [comment]
Good be good ticket for @rtanw10
