### ISSUE TITLE
[FEAT] Finish and review screen - Endless

### ISSUE THREAD

**Issue by rohan-labs** [Preclinify/Tickets#43]
## User Story

**As a** user,  **I want to** click the "finish and review" button so that I can review all the questions that I have done on endless mode **so that** I can learn from the questions I got wrong and struggled on. 

Currently, the button navigates straight back to the home page. This should go to a separate page which provides data on how many questions I answered, how many I got right and calculates a percentage score overall. There should then be an option to either return to the endless mode to review the questions I answered or an option to return back to the home screen

**Comment by Joecey** [comment]
@rohan-labs  @NethminCodes  Do we think this is a CORE feature for closed beta? or a nice-to-have

Devs - I think this could look cool as a modal where it brings up overall stats then gives you the option to go back and review your questions (i.e. closing the modal), or saving your sessions and sending to database. 

My guess is that when you select "Finish and Review," you should not be able to answer/generate any more questions
