### ISSUE TITLE
Ordering modules on the MCQ

### ISSUE THREAD

**Issue by rohan-labs** [Preclinify/Tickets#50]
For the beta launch, it would be ideal to order the modules by the number of questions there are in each module. Currently, it has been done in a random order which may prevent users from accessing all the questions as they would have to randomly look for questions. But if we order it by question quantity, we would ensure users would have a go at all of the questions.

If a module has no questions within it, there should be a redirect saying "coming soon" or something like that. Ideally, this information should be visible to the user before they click - e.g. the card is greyed out or there is accompanying text saying (coming soon).

**Comment by Joecey** [comment]
Completed with #48
